### ISSUE TITLE
saved search

### ISSUE THREAD

**Issue by tlwt** [paperyard/paperyard#13]
The feature to save searches is missing - see page 23 of our initial spec https://drive.google.com/open?id=1sD3jkH6gb8RxGfMhlqmAXnfTfBGMDSh7

**Comment by tlwt** [comment]
1. Search page.
2. user enter keyword to search.
3. user select from autocomplete or press enter to start searching.
4. display results documents.
5. save button visible
6. user click save button.

Saved searches are listed on the sidebar.

**Comment by jannik-kramer** [comment]
> The search should cover the following document fields: Sender, recipient, category, date, notes, tags, number of pages, full text (maybe even more). If a plain text is entered, it will be searched in all document fields. Additionally, there is the possibility to limit the search area. "recipient=Till" searches only in the recipient field. In the mookup there is also an example. In addition, binary operations over several such expressions should be possible (and, or, not, xor, greater/less (date, number of pages)).
